# jwt加密
app:
    jwt:
        secret: springboot

# 代码生成配置
gen:
    # 作者
    author: jjh
    # 自动去除表前缀，默认是true
    autoRemovePre: true
    # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
    packageName: com.business.demo
    # 表前缀(类名不会包含表前缀)
    tablePrefix: sys_

# Mybatis 配置
mybatis:
    # 配置文件路径
    config-location: classpath:mybatis/mybatis-config.xml
    # mapper文件路径
    mapper-locations: classpath:mybatis/mapper/**/*.xml
    # 通配符包路径扫描 mybatis的xml文件中需要写类的全限定名
    type-aliases-package: com.business

# PageHelper分页插件
pagehelper:
    helperDialect: mysql
    page-size-zero: true
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true

# 服务端口
server:
    port: 8084

# Spring配置
spring:
    # 数据源
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        # 数据库驱动
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=GMT%2B8
        password: root
        username: root
        # druid连接池配置
        druid:
            filters: stat
            initial-size: 5
            max-active: 50
            max-pool-prepared-statement-per-connection-size: 20
            max-wait: 60000
            min-idle: 1
            pool-prepared-statements: true
            stat-view-servlet:
                allow: ''
                deny: ''
                enabled: true
                login-password: druid
                login-username: druid
                reset-enable: true
                url-pattern: /druid/*
            test-on-borrow: false
            test-on-return: false
            validation-query: SELECT 1
            validation-query-timeout: 60000
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
                principal-cookie-name: data.platform
                principal-session-name: data.platform
                profile-enable: true
                session-stat-enable: false
                session-stat-max-count: 1000
                url-pattern: /*
    # redis 配置
    redis:
        database: 0
        host: 192.168.1.101
        password: ''
        port: 6379